version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_NAME=workflow-server
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=sekret
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - SECRET_KEY_BASE="${SECRET_KEY_BASE}"
    image: 'suldlss/workflow-server:latest-dev'
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - wfs
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - wfs
networks:
  wfs:
