default: &default
  adapter: postgresql
  encoding: unicode
  database: "<%= ENV.fetch('DATABASE_NAME', 'workflow-server') %>"
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  host: "<%= ENV['DATABASE_HOSTNAME'] %>"
  port: "<%= ENV['DATABASE_PORT'] %>"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
